#include "mesh_exporter.h"
#include <fstream>
#include <iostream>
#include <vector>
#include <cmath>
#include <sstream>

// Реализация OBJExporter
bool OBJExporter::exportMesh(const std::vector<std::vector<double>>& depthData,
    const std::string& filename,
    float scale) {
    if (depthData.empty()) {
        std::cerr << "Ошибка: Пустые данные глубины" << std::endl;
        return false;
    }

    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Ошибка: Не удалось создать файл " << filename << std::endl;
        return false;
    }

    writeHeader(file);
    writeVertices(file, depthData, scale);
    writeNormals(file, depthData, scale);
    writeFaces(file, depthData);

    file.close();
    std::cout << "Файл успешно сохранен: " << filename << std::endl;
    return true;
}

void OBJExporter::writeHeader(std::ofstream& file) {
    file << "# 3D Model from Depth Map\n";
    file << "# Generated by Lab4 - 3D Scene Modeling\n";
    file << "# Format: Wavefront OBJ\n\n";
}

void OBJExporter::writeVertices(std::ofstream& file,
    const std::vector<std::vector<double>>& depthData,
    float scale) {
    int height = depthData.size();
    int width = depthData[0].size();

    file << "# Vertices (" << width * height << " vertices)\n";
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            double depth = depthData[i][j];
            if (depth <= 0.0) continue; // Пропускаем фон

            double x = (j - width / 2.0) * scale;
            double y = depth * scale;
            double z = (i - height / 2.0) * scale;

            file << "v " << x << " " << y << " " << z << "\n";
        }
    }
    file << "\n";
}

void OBJExporter::writeNormals(std::ofstream& file,
    const std::vector<std::vector<double>>& depthData, float scale) {
    int height = depthData.size();
    int width = depthData[0].size();

    file << "# Vertex normals\n";
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            if (depthData[i][j] <= 0.0) continue;

           
            double nx = 0.0, ny = 1.0, nz = 0.0;

            // Более точное вычисление нормали по соседним точкам
            if (i > 0 && j > 0 && i < height - 1 && j < width - 1) {
                double dzdx = (depthData[i][j + 1] - depthData[i][j - 1]) / (2.0 * scale);
                double dzdy = (depthData[i + 1][j] - depthData[i - 1][j]) / (2.0 * scale);

                nx = -dzdx;
                ny = 1.0;
                nz = -dzdy;

                double length = sqrt(nx * nx + ny * ny + nz * nz);
                if (length > 0) {
                    nx /= length;
                    ny /= length;
                    nz /= length;
                }
            }

            file << "vn " << nx << " " << ny << " " << nz << "\n";
        }
    }
    file << "\n";
}

void OBJExporter::writeFaces(std::ofstream& file,
    const std::vector<std::vector<double>>& depthData) {
    int height = depthData.size();
    int width = depthData[0].size();

    file << "# Faces\n";
    int faceCount = 0;

    for (int i = 0; i < height - 1; i++) {
        for (int j = 0; j < width - 1; j++) {
            // Проверяем все 4 вершины квадрата
            if (depthData[i][j] <= 0.0 || depthData[i][j + 1] <= 0.0 ||
                depthData[i + 1][j] <= 0.0 || depthData[i + 1][j + 1] <= 0.0) {
                continue;
            }

            // Индексы вершин
            int v1 = i * width + j + 1;
            int v2 = i * width + j + 2;
            int v3 = (i + 1) * width + j + 1;
            int v4 = (i + 1) * width + j + 2;

            // Первый треугольник
            file << "f " << v1 << "//" << v1
                << " " << v2 << "//" << v2
                << " " << v3 << "//" << v3 << "\n";

            // Второй треугольник
            file << "f " << v2 << "//" << v2
                << " " << v4 << "//" << v4
                << " " << v3 << "//" << v3 << "\n";

            faceCount += 2;
        }
    }

    std::cout << "Создано " << faceCount << " треугольников" << std::endl;
}