#include "mesh_exporter.h"
#include <fstream>
#include <iostream>
#include <vector>
#include <cmath>

bool PLYExporter::exportMesh(const std::vector<std::vector<double>>& depthData,
    const std::string& filename,
    float scale) {
    if (depthData.empty()) {
        std::cerr << "Ошибка: Пустые данные глубины" << std::endl;
        return false;
    }

    int height = static_cast<int>(depthData.size());
    int width = static_cast<int>(depthData[0].size());

    // Подсчет вершин и граней
    int vertexCount = 0;
    int faceCount = 0;

    // Первый проход: подсчет
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            if (depthData[i][j] > 0.0) {
                vertexCount++;
            }
        }
    }

    for (int i = 0; i < height - 1; i++) {
        for (int j = 0; j < width - 1; j++) {
            if (depthData[i][j] > 0.0 && depthData[i][j + 1] > 0.0 &&
                depthData[i + 1][j] > 0.0 && depthData[i + 1][j + 1] > 0.0) {
                faceCount += 2;
            }
        }
    }

    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Ошибка: Не удалось создать файл " << filename << std::endl;
        return false;
    }

    // Записываем заголовок PLY
    writeHeader(file, vertexCount, faceCount);

    // Записываем вершины
    file << "# Вершины\n";
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            if (depthData[i][j] <= 0.0) continue;

            double x = (j - width / 2.0) * scale;
            double y = depthData[i][j] * scale;
            double z = (i - height / 2.0) * scale;

            file << x << " " << y << " " << z << "\n";
        }
    }

    // Записываем грани
    file << "# Грани\n";
    int vertexIndex = 0;
    std::vector<int> vertexIndices(height * width, -1);

    // Создаем маппинг индексов вершин
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            if (depthData[i][j] > 0.0) {
                vertexIndices[i * width + j] = vertexIndex++;
            }
        }
    }

    // Записываем треугольники
    for (int i = 0; i < height - 1; i++) {
        for (int j = 0; j < width - 1; j++) {
            if (depthData[i][j] > 0.0 && depthData[i][j + 1] > 0.0 &&
                depthData[i + 1][j] > 0.0 && depthData[i + 1][j + 1] > 0.0) {

                int idx1 = vertexIndices[i * width + j];
                int idx2 = vertexIndices[i * width + j + 1];
                int idx3 = vertexIndices[(i + 1) * width + j];
                int idx4 = vertexIndices[(i + 1) * width + j + 1];

                if (idx1 >= 0 && idx2 >= 0 && idx3 >= 0) {
                    file << "3 " << idx1 << " " << idx2 << " " << idx3 << "\n";
                }

                if (idx2 >= 0 && idx4 >= 0 && idx3 >= 0) {
                    file << "3 " << idx2 << " " << idx4 << " " << idx3 << "\n";
                }
            }
        }
    }

    file.close();
    std::cout << "PLY файл сохранен: " << filename
        << " (вершин: " << vertexCount << ", граней: " << faceCount << ")" << std::endl;
    return true;
}

void PLYExporter::writeHeader(std::ofstream& file, int vertexCount, int faceCount) {
    file << "ply\n";
    file << "format ascii 1.0\n";
    file << "comment Generated by Lab4 - 3D Scene Modeling\n";
    file << "element vertex " << vertexCount << "\n";
    file << "property float x\n";
    file << "property float y\n";
    file << "property float z\n";
    file << "element face " << faceCount << "\n";
    file << "property list uchar int vertex_indices\n";
    file << "end_header\n";
}